### ISSUE TITLE
Отчет в диссовет РНИИТО за 2018 год

### ISSUE THREAD

**Issue by pussiatoday** [p1m-ortho/xb-track-record#1]
От: Диссовет РНИИТО им. Р.Р. Вредена
Дата: ср, 19 дек. 2018 г. в 11:30

Уважаемые коллеги!
 
Во вложении форма отчета по результатам научной деятельности за 2018 год.
Форму необходимо заполнить до 25.12.2018 года.

**Comment by pussiatoday** [comment]
@SvetlanAlekseevna, я бы хотел Вас завтра перед дежурством.

**Comment by pussiatoday** [comment]
@SvetlanAlekseevna, перевел #2 из заметки в проекте в ишью. Там еще остаются; тоже покажу, в чем идея и как это делается.

**Comment by pussiatoday** [comment]
@SvetlanAlekseevna, а еще потренируем CSV заодно.

**Comment by SvetlanAlekseevna** [comment]
Прогрессируем.

**Comment by pussiatoday** [comment]
Все запланированное обсудили.

Задачу закрою по отправке отчета.

**Comment by pussiatoday** [comment]
Отправил отчет. Готово.
